# Generated by Django 4.2.1 on 2023-07-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capitulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diccionario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(blank=True, max_length=150, null=True)),
                ('link2', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'libro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True)),
                ('verso_start', models.IntegerField(blank=True, null=True)),
                ('verso_end', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Versiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblia.capitulo')),
            ],
            options={
                'db_table': 'versiculo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblia.libro'),
        ),
    ]
